# Updated deploy.yml

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install curl
        run: sudo apt-get install curl
      - name: Execute curl command
        run: |
          curl -L https://unpkg.com/coi-serviceworker@0.1.9 -o coi-serviceworker.min.js
